/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author julio_busarello
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtfVisor = new javax.swing.JTextField();
        jbtnBackspace = new javax.swing.JButton();
        jtbnClear = new javax.swing.JButton();
        jbtnAddMem = new javax.swing.JButton();
        jbtnMult = new javax.swing.JButton();
        jbtnPorc = new javax.swing.JButton();
        jtbDiv = new javax.swing.JButton();
        jbtnMais = new javax.swing.JButton();
        jbtnPonto = new javax.swing.JButton();
        jbtnSub = new javax.swing.JButton();
        jbtnIgual = new javax.swing.JButton();
        jbtnMemoria = new javax.swing.JButton();
        jbtnNove = new javax.swing.JButton();
        jbtnOito = new javax.swing.JButton();
        jbtnSete = new javax.swing.JButton();
        jbtnSeis = new javax.swing.JButton();
        jbtnCinco = new javax.swing.JButton();
        jbtnQuatro = new javax.swing.JButton();
        jbtnTres = new javax.swing.JButton();
        jbtnDois = new javax.swing.JButton();
        jbtnUm = new javax.swing.JButton();
        jbtnZero = new javax.swing.JButton();
        jmbPrincipal = new javax.swing.JMenuBar();
        jmiConversorVelocidade = new javax.swing.JMenu();
        jmbConversorConversor = new javax.swing.JMenuItem();
        jmiSair = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jtfVisor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfVisorActionPerformed(evt);
            }
        });

        jbtnBackspace.setText("<");
        jbtnBackspace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBackspaceActionPerformed(evt);
            }
        });

        jtbnClear.setText("CE");
        jtbnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtbnClearActionPerformed(evt);
            }
        });

        jbtnAddMem.setText("M+");
        jbtnAddMem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAddMemActionPerformed(evt);
            }
        });

        jbtnMult.setText("X");

        jbtnPorc.setText("%");

        jtbDiv.setText("/");

        jbtnMais.setText("+");

        jbtnPonto.setText(",");
        jbtnPonto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPontoActionPerformed(evt);
            }
        });

        jbtnSub.setText("-");

        jbtnIgual.setText("=");
        jbtnIgual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnIgualActionPerformed(evt);
            }
        });

        jbtnMemoria.setText("Memória");

        jbtnNove.setBackground(new java.awt.Color(153, 153, 153));
        jbtnNove.setText("9");

        jbtnOito.setBackground(new java.awt.Color(153, 153, 153));
        jbtnOito.setText("8");

        jbtnSete.setBackground(new java.awt.Color(153, 153, 153));
        jbtnSete.setText("7");

        jbtnSeis.setBackground(new java.awt.Color(153, 153, 153));
        jbtnSeis.setText("6");

        jbtnCinco.setBackground(new java.awt.Color(153, 153, 153));
        jbtnCinco.setText("5");

        jbtnQuatro.setBackground(new java.awt.Color(153, 153, 153));
        jbtnQuatro.setText("4");

        jbtnTres.setBackground(new java.awt.Color(153, 153, 153));
        jbtnTres.setText("3");

        jbtnDois.setBackground(new java.awt.Color(153, 153, 153));
        jbtnDois.setText("2");

        jbtnUm.setBackground(new java.awt.Color(153, 153, 153));
        jbtnUm.setText("1");

        jbtnZero.setBackground(new java.awt.Color(153, 153, 153));
        jbtnZero.setText("0");

        jmiConversorVelocidade.setText("Conversor");

        jmbConversorConversor.setText("Conversor");
        jmbConversorConversor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmbConversorConversorActionPerformed(evt);
            }
        });
        jmiConversorVelocidade.add(jmbConversorConversor);

        jmbPrincipal.add(jmiConversorVelocidade);

        jmiSair.setText("Sair");
        jmbPrincipal.add(jmiSair);

        setJMenuBar(jmbPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbtnMemoria, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jbtnIgual, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jbtnSeis, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jbtnCinco, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jbtnQuatro, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jbtnZero, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jbtnTres, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jbtnDois, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jbtnUm, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jbtnSub, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbtnPonto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbtnMais, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbtnSete, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jbtnOito, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jbtnNove, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jbtnMult, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(jtbDiv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jtfVisor)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jtbnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jbtnBackspace, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbtnAddMem, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jbtnPorc, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jtfVisor, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnBackspace)
                    .addComponent(jtbnClear)
                    .addComponent(jbtnAddMem)
                    .addComponent(jbtnPorc))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnSete)
                    .addComponent(jtbDiv)
                    .addComponent(jbtnOito)
                    .addComponent(jbtnNove)
                    .addComponent(jbtnMult))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnMais)
                    .addComponent(jbtnSeis)
                    .addComponent(jbtnCinco)
                    .addComponent(jbtnQuatro)
                    .addComponent(jbtnZero))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnPonto)
                    .addComponent(jbtnTres)
                    .addComponent(jbtnDois)
                    .addComponent(jbtnUm)
                    .addComponent(jbtnSub))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnMemoria)
                    .addComponent(jbtnIgual))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmbConversorConversorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmbConversorConversorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmbConversorConversorActionPerformed

    private void jtfVisorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfVisorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfVisorActionPerformed

    private void jtbnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtbnClearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtbnClearActionPerformed

    private void jbtnBackspaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBackspaceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnBackspaceActionPerformed

    private void jbtnAddMemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAddMemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnAddMemActionPerformed

    private void jbtnPontoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPontoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnPontoActionPerformed

    private void jbtnIgualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnIgualActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnIgualActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbtnAddMem;
    private javax.swing.JButton jbtnBackspace;
    private javax.swing.JButton jbtnCinco;
    private javax.swing.JButton jbtnDois;
    private javax.swing.JButton jbtnIgual;
    private javax.swing.JButton jbtnMais;
    private javax.swing.JButton jbtnMemoria;
    private javax.swing.JButton jbtnMult;
    private javax.swing.JButton jbtnNove;
    private javax.swing.JButton jbtnOito;
    private javax.swing.JButton jbtnPonto;
    private javax.swing.JButton jbtnPorc;
    private javax.swing.JButton jbtnQuatro;
    private javax.swing.JButton jbtnSeis;
    private javax.swing.JButton jbtnSete;
    private javax.swing.JButton jbtnSub;
    private javax.swing.JButton jbtnTres;
    private javax.swing.JButton jbtnUm;
    private javax.swing.JButton jbtnZero;
    private javax.swing.JMenuItem jmbConversorConversor;
    private javax.swing.JMenuBar jmbPrincipal;
    private javax.swing.JMenu jmiConversorVelocidade;
    private javax.swing.JMenu jmiSair;
    private javax.swing.JButton jtbDiv;
    private javax.swing.JButton jtbnClear;
    private javax.swing.JTextField jtfVisor;
    // End of variables declaration//GEN-END:variables
}
